# iPALM Bead Removal - Python
Beads are automatically removed from iPALM data by first finding the beads in a rendered image and then filtering the localization list to remove localizations near a bead location.

## Bead Removal Instructions
The Python version of bead removal takes as input a single .sav file generated by PeakSelector and outputs a new txt file with localizations corresponding to beads removed. This txt file can be reloaded into PeakSelector for further exploration and visualization of the data.

To use this approach:
1. Load the data of interest into PeakSelector and ensure it is properly filtered. For example, set quality control settings such as sigma rtNPh < 0.06 or set bounds on the unwrapped z value.
2. Open Jupyter notebook with the correct Python environment (described in [One Time Installation](#one-time-installation) below).
3. Set the folder and file name for the .sav file.
4. Optionally adjust the parameters for bead removal:
    - `noiseSize` sets the size in pixels for smoothing the total raw data image
    - `beadSize`  sets the approximate radius of a bead in the total raw data image (pixels)
    - `relThresh` sets a relative threshold on the bandpassed total raw data image
    - `rRemoveX` and `rRemoveY` indicate the size of the region in pixels (133.33 nm/pixel) removed around each bead, in the X & Y directions respectively. Usually `rRemoveY > rRemoveX`.
5. Run the notebook.
6. Check your results using the generated figures! If necessary, adjust your parameters.
7. Use the output txt file for downstream analysis.

## Using txt files with PeakSelector
The output txt files can be reloaded into PeakSelctor through the menu option _Import User ASCII_ by choosing xy coords in pixels, checking the box for headers, and inputting the values 0 to 48 for the data columns (see the file _peakSelector_columnIndices_ for an easy list of values to copy and paste).

## One Time Installation
Any verison of working with Jupyter notebooks that you are comfortable is okay for running the notebook! If you don't know where to get started, these instructions provide a route for installation.

### 1. Install Python
You must have Python on your machine. The AIC workstations use Miniforge, which you can download and install from [conda-forge](https://conda-forge.org/download/).

### 2. Install VS Code
VS Code is an easy interface for working with notebooks. Download and install VS Code from the [Visual Studio Code website](https://code.visualstudio.com/download). This page provides an overview of [how to work with Jupyter notebooks in VS code](https://code.visualstudio.com/docs/datascience/jupyter-notebooks) if you would like to learn more about the interface.

### 3. Create Conda Environment
To work with this notebook, you will need a Python environment that contains scipy, matplotlib, numpy, skimage, and pandas. We suggest working with conda environments for this ([see this blog post about working with conda in general](https://focalplane.biologists.com/2022/12/08/managing-scientific-python-environments-using-conda-mamba-and-friends/)).

To create an environment on Windows, download the `beadRemoval.yml` file from code repository. Open up a terminal (either by opening Miniforge or opening a terminal in VS Code) and navigate to the folder containing this yml file (use `cd` to change directories). Then run the following command:

`conda env create -f beadRemoval.yml`

Let the environment download and install any necessary packages. Once it is done, you will be able to select the 'beadRemoval' environment from the upper right corner of your Jupyter notebook in VS Code.
